config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'time_sheets#index'  
  resources :time_sheets, only: %i[index new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_sheet.rb
class TimeSheet < ApplicationRecord
  validates :working_date, :start_time, :end_time, :working_fee, presence: true
  validates :working_date, uniqueness: true

  validate :validate_future_day
  validate :validate_end_time
  
  def validate_future_day
    if working_date > DateTime.now
      errors.add(:working_date, "must be not in the future")
    end
  end

  def validate_end_time
    if end_time < start_time
      errors.add(:end_time ," cannot be before start time")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/time_sheets_controller.rb
class TimeSheetsController < ApplicationController
  WEEK_DAYS = {
    '0': 'GROUP_3', # Sunday
    '1': 'GROUP_1', # Monday
    '2': 'GROUP_2', # Tuesday
    '3': 'GROUP_1', # Wednesday
    '4': 'GROUP_2', # Thursday
    '5': 'GROUP_1', # Friday
    '6': 'GROUP_3', # Saturday
  }
  TIME = {
    GROUP_1: {
      start_time: 7,
      end_time: 19
    },
    GROUP_2: {
      start_time: 5,
      end_time: 17
    },
    GROUP_3: {
      start_time: 8,
      end_time: 16
    }
  }
  FEE = {
    GROUP_1: 22,
    GROUP_2: 25,
    GROUP_3: 47
  }
  OT_FEE = {
    GROUP_1: 34,
    GROUP_2: 35,
    GROUP_3: 47
  }

  def index
    @time_sheets = TimeSheet.order(:working_date)
  end

  def new
    @time_sheet = TimeSheet.new
  end

  def create
    # date
    input_day = time_sheet_params["working_date(3i)"]
    input_month = time_sheet_params["working_date(2i)"]
    input_year = time_sheet_params["working_date(1i)"]
    date = Date.new(input_year.to_i, input_month.to_i, input_day.to_i)
    group = WEEK_DAYS[date.wday.to_s.to_sym]

    # start time
    input_st_time_h = time_sheet_params["start_time(4i)"].to_i
    input_st_time_m = time_sheet_params["start_time(5i)"].to_f
    start_time = change_time_format(input_st_time_h, input_st_time_m)
    formt_time_start = "#{input_st_time_h}:#{input_st_time_m}"

    # end time
    input_end_time_h = time_sheet_params["end_time(4i)"].to_i
    input_end_time_m = time_sheet_params["end_time(5i)"].to_f
    end_time = change_time_format(input_end_time_h, input_end_time_m)
    formt_time_end = "#{input_end_time_h}:#{input_end_time_m}"

    # working time and amount
    working_time = detect_working_time(start_time, end_time, group)
    total_fee = calculate_fee(working_time, group)
    @time_sheet = TimeSheet.new(working_date: date, start_time: formt_time_start, end_time: formt_time_end, working_fee: total_fee)
    respond_to do |format|
      if @time_sheet.save
        format.html { redirect_to time_sheets_path, notice: "Time sheet was successfully created." }
        format.json { render :show, status: :created, location: @time_sheet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  def detect_working_time(start_time, end_time, group)
    default_st_time = TIME[group.to_sym][:start_time]
    default_end_time = TIME[group.to_sym][:end_time]
    ot_before_start_time = default_st_time > start_time ? default_st_time.to_f - start_time.to_f : 0
    ot_after_end_time = default_end_time < end_time ? end_time.to_f - default_end_time.to_f : 0
    
    {
      normal_time: end_time - start_time - ot_before_start_time - ot_after_end_time,
      ot_time: ot_before_start_time + ot_after_end_time
    }
  end

  def calculate_fee(working_time, group)
    normal_fee = FEE[group.to_sym]
    ot_fee = OT_FEE[group.to_sym]
    normal_fee = working_time[:normal_time] * normal_fee
    ot_paid = working_time[:ot_time] * ot_fee

    normal_fee + ot_paid
  end

  def change_time_format(hour, minute)
    format_minute = 0
    if minute != 0
      format_minute = (minute/60).round(2)
    end

    hour + format_minute
  end

  private

  def time_sheet_params
    params.require(:time_sheet).permit(:working_date, :start_time, :end_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeployTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/time_sheets/index.html.erb
<%= link_to "Create new Timesheet", new_time_sheet_path, method: :get %>
<% if @time_sheets.count == 0%>
<h1>There no time sheet</h1>
<% else %>
<p style="color: green" ><%= notice %></p>
<h1>Timesheet Entries</h1>
  <% @time_sheets.each do |time_sheet| %>
    <%= time_sheet.working_date.strftime("%d %m %Y") %>: <%= time_sheet.start_time.strftime('%H:%M') %> - <%= time_sheet.end_time.strftime('%H:%M') %> $<%= time_sheet.working_fee.round(2) %>  
    <br>
  <% end %>
<% end %>

app/views/time_sheets/new.html.erb
<h1>Create New Timesheet</h1>

<%= form_with(model: @time_sheet) do |form| %>
  
  <% if @time_sheet.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @time_sheet.errors.each do |error| %>
          <li style="color:red"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :working_date %>
    <%= form.date_select :working_date %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.time_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.time_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to "Back", time_sheets_path, method: :get %>